steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/overture-maps-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/overture-maps-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'overture-maps-api',
         '--image', 'gcr.io/$PROJECT_ID/overture-maps-api',
         '--platform', 'managed',
         '--region', 'us-central1',  # Change region if necessary
         '--allow-unauthenticated',
         '--memory', '512Mi',
         '--port', '8080',
         '--set-env-vars', 'NODE_ENV=production']
images:
- 'gcr.io/$PROJECT_ID/overture-maps-api'
